### PR TITLE
remove leanpub-specific stuff

### PR DESCRIPTION
**Pull request by gernotstarke**
remove manuscript folder

### CODE REVIEW

**Comment by programming-wolf** [comment]
Please don't, I currently need that file :) I'm checking book references in my branch and I already copied some references that I needed from this file.

**Comment by gernotstarke** [comment]
then approve later... but we shouldn't keep this old stuff forever...

**Comment by programming-wolf** [comment]
Yes, I will remove it once I'm done with my check (5 letters left)

**Comment by programming-wolf** [comment]
Will be done with #171

**Pull request closed without merging**
