### PR TITLE
Migration of terms K ... Z

### PR DESCRIPTION
**Pull request by ichsteffen**

### CODE REVIEW

**Comment by ichsteffen** [comment]
work in progress - please do not merge at the moment

**Comment by ichsteffen** [comment]
Done... could be merged. 

Some issues with images are left, but migration of term-files into adoc should be complete.

**Comment by programming-wolf** [comment]
Could you please resolve the conflicts first? 

We have to invite @ichsteffen for a drink, @gernotstarke , for the work he put into this :)

**Comment by ichsteffen** [comment]
To be honest, I have no idea how to technically resolve the conflict. My git skills are rudimentary.

**Comment by programming-wolf** [comment]
Ok, I'll try the resolve conflict feature in GitHub. 🙂

**Pull request merged**
